/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AMFEventLog service. Represents a row in the &quot;amfeventlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.registration.model.impl.AMFEventLogModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.registration.model.impl.AMFEventLogImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AMFEventLog
 * @generated
 */
@ProviderType
public interface AMFEventLogModel
	extends BaseModel<AMFEventLog>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf event log model instance should use the {@link AMFEventLog} interface instead.
	 */

	/**
	 * Returns the primary key of this amf event log.
	 *
	 * @return the primary key of this amf event log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf event log.
	 *
	 * @param primaryKey the primary key of this amf event log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this amf event log.
	 *
	 * @return the uuid of this amf event log
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this amf event log.
	 *
	 * @param uuid the uuid of this amf event log
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the amf event log ID of this amf event log.
	 *
	 * @return the amf event log ID of this amf event log
	 */
	public long getAmfEventLogId();

	/**
	 * Sets the amf event log ID of this amf event log.
	 *
	 * @param amfEventLogId the amf event log ID of this amf event log
	 */
	public void setAmfEventLogId(long amfEventLogId);

	/**
	 * Returns the company ID of this amf event log.
	 *
	 * @return the company ID of this amf event log
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this amf event log.
	 *
	 * @param companyId the company ID of this amf event log
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this amf event log.
	 *
	 * @return the create date of this amf event log
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this amf event log.
	 *
	 * @param createDate the create date of this amf event log
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this amf event log.
	 *
	 * @return the modified date of this amf event log
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this amf event log.
	 *
	 * @param modifiedDate the modified date of this amf event log
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group ID of this amf event log.
	 *
	 * @return the group ID of this amf event log
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this amf event log.
	 *
	 * @param groupId the group ID of this amf event log
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this amf event log.
	 *
	 * @return the user ID of this amf event log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this amf event log.
	 *
	 * @param userId the user ID of this amf event log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amf event log.
	 *
	 * @return the user uuid of this amf event log
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amf event log.
	 *
	 * @param userUuid the user uuid of this amf event log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the last login date of this amf event log.
	 *
	 * @return the last login date of this amf event log
	 */
	public Date getLastLoginDate();

	/**
	 * Sets the last login date of this amf event log.
	 *
	 * @param lastLoginDate the last login date of this amf event log
	 */
	public void setLastLoginDate(Date lastLoginDate);

	/**
	 * Returns the last login ip of this amf event log.
	 *
	 * @return the last login ip of this amf event log
	 */
	@AutoEscape
	public String getLastLoginIP();

	/**
	 * Sets the last login ip of this amf event log.
	 *
	 * @param lastLoginIP the last login ip of this amf event log
	 */
	public void setLastLoginIP(String lastLoginIP);

	/**
	 * Returns the status of this amf event log.
	 *
	 * @return the status of this amf event log
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this amf event log.
	 *
	 * @param status the status of this amf event log
	 */
	public void setStatus(String status);

}