/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.newsletters.core.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Articles service. Represents a row in the &quot;articles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.newsletters.core.model.impl.ArticlesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.newsletters.core.model.impl.ArticlesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Articles
 * @generated
 */
@ProviderType
public interface ArticlesModel
	extends BaseModel<Articles>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a articles model instance should use the {@link Articles} interface instead.
	 */

	/**
	 * Returns the primary key of this articles.
	 *
	 * @return the primary key of this articles
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this articles.
	 *
	 * @param primaryKey the primary key of this articles
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this articles.
	 *
	 * @return the uuid of this articles
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this articles.
	 *
	 * @param uuid the uuid of this articles
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the article ID of this articles.
	 *
	 * @return the article ID of this articles
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this articles.
	 *
	 * @param articleId the article ID of this articles
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the company ID of this articles.
	 *
	 * @return the company ID of this articles
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this articles.
	 *
	 * @param companyId the company ID of this articles
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this articles.
	 *
	 * @return the user ID of this articles
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this articles.
	 *
	 * @param userId the user ID of this articles
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this articles.
	 *
	 * @return the user uuid of this articles
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this articles.
	 *
	 * @param userUuid the user uuid of this articles
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this articles.
	 *
	 * @return the user name of this articles
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this articles.
	 *
	 * @param userName the user name of this articles
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this articles.
	 *
	 * @return the create date of this articles
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this articles.
	 *
	 * @param createDate the create date of this articles
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this articles.
	 *
	 * @return the modified date of this articles
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this articles.
	 *
	 * @param modifiedDate the modified date of this articles
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the issue number of this articles.
	 *
	 * @return the issue number of this articles
	 */
	public int getIssueNumber();

	/**
	 * Sets the issue number of this articles.
	 *
	 * @param issueNumber the issue number of this articles
	 */
	public void setIssueNumber(int issueNumber);

	/**
	 * Returns the title of this articles.
	 *
	 * @return the title of this articles
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this articles.
	 *
	 * @param title the title of this articles
	 */
	public void setTitle(String title);

	/**
	 * Returns the author of this articles.
	 *
	 * @return the author of this articles
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this articles.
	 *
	 * @param author the author of this articles
	 */
	public void setAuthor(String author);

	/**
	 * Returns the order of this articles.
	 *
	 * @return the order of this articles
	 */
	public int getOrder();

	/**
	 * Sets the order of this articles.
	 *
	 * @param order the order of this articles
	 */
	public void setOrder(int order);

	/**
	 * Returns the content of this articles.
	 *
	 * @return the content of this articles
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this articles.
	 *
	 * @param content the content of this articles
	 */
	public void setContent(String content);

}