/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AMFIssue service. Represents a row in the &quot;amf_issue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.newsletter.model.impl.AMFIssueModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.newsletter.model.impl.AMFIssueImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AMFIssue
 * @generated
 */
@ProviderType
public interface AMFIssueModel
	extends BaseModel<AMFIssue>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf issue model instance should use the {@link AMFIssue} interface instead.
	 */

	/**
	 * Returns the primary key of this amf issue.
	 *
	 * @return the primary key of this amf issue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf issue.
	 *
	 * @param primaryKey the primary key of this amf issue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this amf issue.
	 *
	 * @return the uuid of this amf issue
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this amf issue.
	 *
	 * @param uuid the uuid of this amf issue
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the amf issue ID of this amf issue.
	 *
	 * @return the amf issue ID of this amf issue
	 */
	public long getAmfIssueId();

	/**
	 * Sets the amf issue ID of this amf issue.
	 *
	 * @param amfIssueId the amf issue ID of this amf issue
	 */
	public void setAmfIssueId(long amfIssueId);

	/**
	 * Returns the group ID of this amf issue.
	 *
	 * @return the group ID of this amf issue
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this amf issue.
	 *
	 * @param groupId the group ID of this amf issue
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user group ID of this amf issue.
	 *
	 * @return the user group ID of this amf issue
	 */
	public long getUserGroupId();

	/**
	 * Sets the user group ID of this amf issue.
	 *
	 * @param userGroupId the user group ID of this amf issue
	 */
	public void setUserGroupId(long userGroupId);

	/**
	 * Returns the company ID of this amf issue.
	 *
	 * @return the company ID of this amf issue
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this amf issue.
	 *
	 * @param companyId the company ID of this amf issue
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this amf issue.
	 *
	 * @return the user ID of this amf issue
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this amf issue.
	 *
	 * @param userId the user ID of this amf issue
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amf issue.
	 *
	 * @return the user uuid of this amf issue
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amf issue.
	 *
	 * @param userUuid the user uuid of this amf issue
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this amf issue.
	 *
	 * @return the user name of this amf issue
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this amf issue.
	 *
	 * @param userName the user name of this amf issue
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this amf issue.
	 *
	 * @return the create date of this amf issue
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this amf issue.
	 *
	 * @param createDate the create date of this amf issue
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this amf issue.
	 *
	 * @return the modified date of this amf issue
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this amf issue.
	 *
	 * @param modifiedDate the modified date of this amf issue
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the issued date of this amf issue.
	 *
	 * @return the issued date of this amf issue
	 */
	public Date getIssuedDate();

	/**
	 * Sets the issued date of this amf issue.
	 *
	 * @param issuedDate the issued date of this amf issue
	 */
	public void setIssuedDate(Date issuedDate);

	/**
	 * Returns the issue number of this amf issue.
	 *
	 * @return the issue number of this amf issue
	 */
	public int getIssueNumber();

	/**
	 * Sets the issue number of this amf issue.
	 *
	 * @param issueNumber the issue number of this amf issue
	 */
	public void setIssueNumber(int issueNumber);

	/**
	 * Returns the title of this amf issue.
	 *
	 * @return the title of this amf issue
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this amf issue.
	 *
	 * @param title the title of this amf issue
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this amf issue.
	 *
	 * @return the description of this amf issue
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this amf issue.
	 *
	 * @param description the description of this amf issue
	 */
	public void setDescription(String description);

}