/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.newsletter.service.base;

import com.amf.newsletter.model.AMFArticle;
import com.amf.newsletter.service.AMFArticleLocalService;
import com.amf.newsletter.service.persistence.AMFArticlePersistence;
import com.amf.newsletter.service.persistence.AMFIssuePersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the amf article local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.amf.newsletter.service.impl.AMFArticleLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.amf.newsletter.service.impl.AMFArticleLocalServiceImpl
 * @generated
 */
public abstract class AMFArticleLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AMFArticleLocalService, AopService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AMFArticleLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.amf.newsletter.service.AMFArticleLocalServiceUtil</code>.
	 */

	/**
	 * Adds the amf article to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMFArticleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amfArticle the amf article
	 * @return the amf article that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AMFArticle addAMFArticle(AMFArticle amfArticle) {
		amfArticle.setNew(true);

		return amfArticlePersistence.update(amfArticle);
	}

	/**
	 * Creates a new amf article with the primary key. Does not add the amf article to the database.
	 *
	 * @param amfArticleId the primary key for the new amf article
	 * @return the new amf article
	 */
	@Override
	@Transactional(enabled = false)
	public AMFArticle createAMFArticle(long amfArticleId) {
		return amfArticlePersistence.create(amfArticleId);
	}

	/**
	 * Deletes the amf article with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMFArticleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amfArticleId the primary key of the amf article
	 * @return the amf article that was removed
	 * @throws PortalException if a amf article with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AMFArticle deleteAMFArticle(long amfArticleId)
		throws PortalException {

		return amfArticlePersistence.remove(amfArticleId);
	}

	/**
	 * Deletes the amf article from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMFArticleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amfArticle the amf article
	 * @return the amf article that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AMFArticle deleteAMFArticle(AMFArticle amfArticle) {
		return amfArticlePersistence.remove(amfArticle);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AMFArticle.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return amfArticlePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.amf.newsletter.model.impl.AMFArticleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return amfArticlePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.amf.newsletter.model.impl.AMFArticleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return amfArticlePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return amfArticlePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return amfArticlePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AMFArticle fetchAMFArticle(long amfArticleId) {
		return amfArticlePersistence.fetchByPrimaryKey(amfArticleId);
	}

	/**
	 * Returns the amf article with the matching UUID and company.
	 *
	 * @param uuid the amf article's UUID
	 * @param companyId the primary key of the company
	 * @return the matching amf article, or <code>null</code> if a matching amf article could not be found
	 */
	@Override
	public AMFArticle fetchAMFArticleByUuidAndCompanyId(
		String uuid, long companyId) {

		return amfArticlePersistence.fetchByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the amf article with the primary key.
	 *
	 * @param amfArticleId the primary key of the amf article
	 * @return the amf article
	 * @throws PortalException if a amf article with the primary key could not be found
	 */
	@Override
	public AMFArticle getAMFArticle(long amfArticleId) throws PortalException {
		return amfArticlePersistence.findByPrimaryKey(amfArticleId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(amfArticleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AMFArticle.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("amfArticleId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			amfArticleLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AMFArticle.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"amfArticleId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(amfArticleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AMFArticle.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("amfArticleId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<AMFArticle>() {

				@Override
				public void performAction(AMFArticle amfArticle)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, amfArticle);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(AMFArticle.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return amfArticlePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return amfArticleLocalService.deleteAMFArticle(
			(AMFArticle)persistedModel);
	}

	public BasePersistence<AMFArticle> getBasePersistence() {
		return amfArticlePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return amfArticlePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the amf article with the matching UUID and company.
	 *
	 * @param uuid the amf article's UUID
	 * @param companyId the primary key of the company
	 * @return the matching amf article
	 * @throws PortalException if a matching amf article could not be found
	 */
	@Override
	public AMFArticle getAMFArticleByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return amfArticlePersistence.findByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns a range of all the amf articles.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.amf.newsletter.model.impl.AMFArticleModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of amf articles
	 * @param end the upper bound of the range of amf articles (not inclusive)
	 * @return the range of amf articles
	 */
	@Override
	public List<AMFArticle> getAMFArticles(int start, int end) {
		return amfArticlePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of amf articles.
	 *
	 * @return the number of amf articles
	 */
	@Override
	public int getAMFArticlesCount() {
		return amfArticlePersistence.countAll();
	}

	/**
	 * Updates the amf article in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AMFArticleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amfArticle the amf article
	 * @return the amf article that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AMFArticle updateAMFArticle(AMFArticle amfArticle) {
		return amfArticlePersistence.update(amfArticle);
	}

	/**
	 */
	@Override
	public void addAMFIssueAMFArticle(long amfIssueId, long amfArticleId) {
		amfIssuePersistence.addAMFArticle(amfIssueId, amfArticleId);
	}

	/**
	 */
	@Override
	public void addAMFIssueAMFArticle(long amfIssueId, AMFArticle amfArticle) {
		amfIssuePersistence.addAMFArticle(amfIssueId, amfArticle);
	}

	/**
	 */
	@Override
	public void addAMFIssueAMFArticles(long amfIssueId, long[] amfArticleIds) {
		amfIssuePersistence.addAMFArticles(amfIssueId, amfArticleIds);
	}

	/**
	 */
	@Override
	public void addAMFIssueAMFArticles(
		long amfIssueId, List<AMFArticle> amfArticles) {

		amfIssuePersistence.addAMFArticles(amfIssueId, amfArticles);
	}

	/**
	 */
	@Override
	public void clearAMFIssueAMFArticles(long amfIssueId) {
		amfIssuePersistence.clearAMFArticles(amfIssueId);
	}

	/**
	 */
	@Override
	public void deleteAMFIssueAMFArticle(long amfIssueId, long amfArticleId) {
		amfIssuePersistence.removeAMFArticle(amfIssueId, amfArticleId);
	}

	/**
	 */
	@Override
	public void deleteAMFIssueAMFArticle(
		long amfIssueId, AMFArticle amfArticle) {

		amfIssuePersistence.removeAMFArticle(amfIssueId, amfArticle);
	}

	/**
	 */
	@Override
	public void deleteAMFIssueAMFArticles(
		long amfIssueId, long[] amfArticleIds) {

		amfIssuePersistence.removeAMFArticles(amfIssueId, amfArticleIds);
	}

	/**
	 */
	@Override
	public void deleteAMFIssueAMFArticles(
		long amfIssueId, List<AMFArticle> amfArticles) {

		amfIssuePersistence.removeAMFArticles(amfIssueId, amfArticles);
	}

	/**
	 * Returns the amfIssueIds of the amf issues associated with the amf article.
	 *
	 * @param amfArticleId the amfArticleId of the amf article
	 * @return long[] the amfIssueIds of amf issues associated with the amf article
	 */
	@Override
	public long[] getAMFIssuePrimaryKeys(long amfArticleId) {
		return amfArticlePersistence.getAMFIssuePrimaryKeys(amfArticleId);
	}

	/**
	 */
	@Override
	public List<AMFArticle> getAMFIssueAMFArticles(long amfIssueId) {
		return amfArticlePersistence.getAMFIssueAMFArticles(amfIssueId);
	}

	/**
	 */
	@Override
	public List<AMFArticle> getAMFIssueAMFArticles(
		long amfIssueId, int start, int end) {

		return amfArticlePersistence.getAMFIssueAMFArticles(
			amfIssueId, start, end);
	}

	/**
	 */
	@Override
	public List<AMFArticle> getAMFIssueAMFArticles(
		long amfIssueId, int start, int end,
		OrderByComparator<AMFArticle> orderByComparator) {

		return amfArticlePersistence.getAMFIssueAMFArticles(
			amfIssueId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getAMFIssueAMFArticlesCount(long amfIssueId) {
		return amfIssuePersistence.getAMFArticlesSize(amfIssueId);
	}

	/**
	 */
	@Override
	public boolean hasAMFIssueAMFArticle(long amfIssueId, long amfArticleId) {
		return amfIssuePersistence.containsAMFArticle(amfIssueId, amfArticleId);
	}

	/**
	 */
	@Override
	public boolean hasAMFIssueAMFArticles(long amfIssueId) {
		return amfIssuePersistence.containsAMFArticles(amfIssueId);
	}

	/**
	 */
	@Override
	public void setAMFIssueAMFArticles(long amfIssueId, long[] amfArticleIds) {
		amfIssuePersistence.setAMFArticles(amfIssueId, amfArticleIds);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AMFArticleLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		amfArticleLocalService = (AMFArticleLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AMFArticleLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AMFArticle.class;
	}

	protected String getModelClassName() {
		return AMFArticle.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = amfArticlePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected AMFArticleLocalService amfArticleLocalService;

	@Reference
	protected AMFArticlePersistence amfArticlePersistence;

	@Reference
	protected AMFIssuePersistence amfIssuePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}